firebase:
  database-url: ${FIREBASE_DATABASE_URL}
  service-account-json: ${FIREBASE_SERVICE_ACCOUNT_JSON}

spring:
  application:
    name: artisan-iron-web
  thymeleaf:
    cache: false
    mode: HTML
  mail:
    host: smtp.sendgrid.net
    port: 587
    username: apikey
    password: ${MAIL_PASSWORD:}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=100,expireAfterWrite=10m

server:
  port: 8080
  servlet:
    context-path: /

logging:
  level:
    root: INFO
    com.artisaniron: DEBUG
    com.google.firebase: DEBUG
